11/2FB対応
extreal-dev/Extreal.Core.SceneTransition pull request #10
Opened 2022-11-06 09:18 UTC by kiyohome

# Describe Your Changes (なんの変更を加えましたか?)

# What did you verify? (何を確認しましたか?)

- [ ] Verified that processing for invalid arguments and invalid method calls is included (無効な引数や無効なメソッド呼び出しに対する処理が入っていることを確認しました)
- [ ] Verified that debug logs are being output to show behavior at runtime (実行時の動作が分かるようなデバッグログを出力していることを確認しました)
- [ ] Verified that no problems were found in the static analysis (静的解析で問題が見つからないことを確認しました)
- [ ] Verified that all tests succeeded (全てのテストが成功することを確認しました)
- [ ] Verified that test coverage is 100% (テストカバレッジが100%になることを確認しました)

# Message to reviewers (レビュアーへのメッセージ)

2022-11-07 01:47 UTC, sus-taguchi-t requested changes

2022-11-07 01:47 UTC, sus-taguchi-t commented on Tests/Runtime/StageConfig.cs
> +    }
`commonUnitySceneNames` -> `commonScenes`
`scenes` -> `stages`

2022-11-07 01:47 UTC, sus-taguchi-t commented on Tests/Runtime/StageNavigatorTest.cs
> +            // Transition to FirstScene without leaving history
`FirstScene` -> `FirstStage`
他のコメントアウトも同じ。

2022-11-08 00:50 UTC, kiyohome commented on Tests/Runtime/StageConfig.cs
> +    }
すみません、修正しました！
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/10/commits/ded08e0284f5ab9f03e82f5ad0c57fc606b4d629

2022-11-08 00:50 UTC, kiyohome commented on Tests/Runtime/StageNavigatorTest.cs
> +            // Transition to FirstScene without leaving history
すみません、修正しました。
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/10/commits/a5e1e421e8283476fdb23f8c89522fdb6282825c

2022-11-08 00:57 UTC, kiyohome commented on Runtime/StageNavigator.cs
> +                throw new InvalidOperationException("there is no scene transition history");
`scene` transition history
→`stage` transition history

2022-11-08 01:03 UTC, kiyohome commented on Runtime/StageNavigator.cs
> +                throw new InvalidOperationException("there is no scene transition history");
修正しました！
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/10/commits/97e453e120fd3b5f9575da677737c3736ca935e2

2022-11-08 04:21 UTC, sus-taguchi-t commented on Runtime/StageNavigator.cs
> +                throw new InvalidOperationException("there is no scene transition history");
確認しました！

2022-11-08 04:22 UTC, sus-taguchi-t commented on Tests/Runtime/StageConfig.cs
> +    }
確認しました！

2022-11-08 04:24 UTC, sus-taguchi-t requested changes

2022-11-08 04:24 UTC, sus-taguchi-t commented on Tests/Runtime/StageNavigatorTest.cs
> +            // Transition back to Third according to history
`Third` -> `ThirdStage`

2022-11-08 04:24 UTC, sus-taguchi-t commented on Tests/Runtime/StageNavigatorTest.cs
> +            // Transition to FirstScene without leaving history
確認しました！

2022-11-08 04:27 UTC, sus-taguchi-t commented on Tests/Runtime/StageNavigatorTest.cs
> +            // Transition back to Third according to history
修正しました！
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/10/commits/252ef673f9165cdf0198f1d35dffd1eac22fa175

2022-11-08 04:28 UTC, sus-taguchi-t approved these changes

2022-11-08 04:28 UTC, merged