StageNavigation の改善
extreal-dev/Extreal.Core.SceneTransition pull request #12
Opened 2022-11-30 08:24 UTC by sus-taguchi-t

# Describe Your Changes (なんの変更を加えましたか?)

- `StageNavigation` の戻れるステージ遷移機能を削除する
- `StageNavigation` のインタフェースを無くす
- `IStageConfig` の実装クラスは同じ実装になるので Base クラスを提供する
- イベント通知を `UniRx` ベースとする

# What did you verify? (何を確認しましたか?)

- [x] Verified that processing for invalid arguments and invalid method calls is included (無効な引数や無効なメソッド呼び出しに対する処理が入っていることを確認しました)
- [x] Verified that debug logs are being output to show behavior at runtime (実行時の動作が分かるようなデバッグログを出力していることを確認しました)
- [x] Verified that no problems were found in the static analysis (静的解析で問題が見つからないことを確認しました)
- [x] Verified that all tests succeeded (全てのテストが成功することを確認しました)
- [x] Verified that test coverage is 100% (テストカバレッジが100%になることを確認しました)

# Message to reviewers (レビュアーへのメッセージ)

- [ ] コーディングに特に問題はないですか？

2022-11-30 08:26 UTC, sus-taguchi-t commented on Runtime/IStageConfig.cs
>      public interface IStageConfig<TStage, TScene>
`StageConfigBase` クラスを用意したので、このインターフェースは削除しますか？

2022-11-30 08:27 UTC, sus-taguchi-t commented on Runtime/Extreal.Core.StageNavigation.asmdef
> +        "Extreal.Framework.Analyzer"
完成時に削除します。

2022-12-01 00:58 UTC, kiyohome requested changes

2022-12-01 00:58 UTC, kiyohome commented on Runtime/IStageConfig.cs
>      public interface IStageConfig<TStage, TScene>
StageNvigatorがStageConfigBaseに依存するのは微妙なのでインタフェースは残しましょう。

2022-12-01 00:58 UTC, kiyohome commented on Runtime/IStageConfig.cs
>      public interface IStageConfig<TStage, TScene>
Baseクラスはあくまでアプリ実装の負荷を下げる目的という位置づけです。

2022-12-01 00:58 UTC, kiyohome commented on Runtime/StageNavigator.cs
> +        public async UniTask TransitionAsync(TStage stage)
stageを置き換えるので`ReplaceAsync`のままの方がよくないでしょうか？
transitionとするとUnityのtransitionを期待されるのでAPIとしては使ってなかったと思います。

2022-12-01 00:58 UTC, kiyohome commented on Runtime/StageNavigator.cs
> +            onStageTransitioning.Dispose();
Disposeメソッドのカバレッジが未達で出たのですが私の環境だけでしょうか？

2022-12-01 00:58 UTC, kiyohome commented on Runtime/StageNavigator.cs
>          private static readonly ELogger Logger
ここもカバレッジが通ってないですね？
前からですかね？

2022-12-01 01:00 UTC, sus-taguchi-t commented on Runtime/IStageConfig.cs
>      public interface IStageConfig<TStage, TScene>
分かりました！

2022-12-01 01:16 UTC, kiyohome requested changes

2022-12-01 01:16 UTC, kiyohome commented on Tests/Runtime/StageNavigatorTest.cs
> +        private readonly CompositeDisposable disposables = new CompositeDisposable();
`Field disposables should be disposed.`
と出てるのでpragma入れときませんか？

2022-12-01 01:18 UTC, sus-taguchi-t commented on Runtime/StageNavigator.cs
> +        public async UniTask TransitionAsync(TStage stage)
分かりました。戻しておきます。

2022-12-01 01:18 UTC, sus-taguchi-t commented on Runtime/StageNavigator.cs
> +            onStageTransitioning.Dispose();
私の環境でも通っていなかったです。
テストを修正します。

2022-12-01 01:20 UTC, sus-taguchi-t commented on Runtime/StageNavigator.cs
>          private static readonly ELogger Logger
ここは私の環境では通っています。
もしかしたら履歴が悪さをしている可能性があるので、`Code Coverage` のタブ内にある `Clear Data` や `Clear History` を実行してからテストしてみると良いかもしれません。

2022-12-01 01:20 UTC, sus-taguchi-t commented on Tests/Runtime/StageNavigatorTest.cs
> +        private readonly CompositeDisposable disposables = new CompositeDisposable();
入れておきます。

2022-12-01 01:23 UTC, sus-taguchi-t commented on Runtime/StageNavigator.cs
> +        public async UniTask TransitionAsync(TStage stage)
修正しました！
https://github.com/extreal-dev/Extreal.Core.StageNavigation/pull/12/commits/d08f2c7d648eec41903f5c1274acc376d3595a51

2022-12-01 01:23 UTC, sus-taguchi-t commented on Runtime/StageNavigator.cs
> +            onStageTransitioning.Dispose();
修正しました！
https://github.com/extreal-dev/Extreal.Core.StageNavigation/pull/12/commits/d08f2c7d648eec41903f5c1274acc376d3595a51

2022-12-01 01:23 UTC, sus-taguchi-t commented on Tests/Runtime/StageNavigatorTest.cs
> +        private readonly CompositeDisposable disposables = new CompositeDisposable();
修正しました！
https://github.com/extreal-dev/Extreal.Core.StageNavigation/pull/12/commits/d08f2c7d648eec41903f5c1274acc376d3595a51

2022-12-01 01:28 UTC, kiyohome commented on Runtime/StageNavigator.cs
> +        public async UniTask TransitionAsync(TStage stage)
LGTM

2022-12-01 01:28 UTC, kiyohome commented on Runtime/StageNavigator.cs
> +            onStageTransitioning.Dispose();
LGTM

2022-12-01 01:29 UTC, kiyohome commented on Runtime/StageNavigator.cs
>          private static readonly ELogger Logger
今回は通りました！

2022-12-01 01:29 UTC, kiyohome commented on Tests/Runtime/StageNavigatorTest.cs
> +        private readonly CompositeDisposable disposables = new CompositeDisposable();
LGTM

2022-12-01 01:30 UTC, kiyohome approved these changes

2022-12-01 01:34 UTC, sus-taguchi-t commented on Runtime/Extreal.Core.StageNavigation.asmdef
> +        "Extreal.Framework.Analyzer"
削除しました！
https://github.com/extreal-dev/Extreal.Core.StageNavigation/pull/12/commits/b3fd9eb5e7432b83c62381a61a6efa504e84870e

2022-12-01 01:35 UTC, merged