FW利用者がSceneTransitionを使えるようにする
extreal-dev/Extreal.Core.SceneTransition pull request #3
Opened 2022-10-19 07:57 UTC by sus-taguchi-t

close #2 

# Describe Your Changes (なんの変更を加えましたか?)

- [x] フォーマッタを導入した
- [x] 静的解析を導入した
- [x] SceneTransition のテストを作成した
- [x] SceneTransition のライブラリを作成した
- [x] C# ドキュメントを作成した
- [ ] ~~コントリビュータに向けてライブラリ開発のセットアップ方法を README.md に記述した~~

# What operation was verified? (なんの動作を確認しましたか?)

- [x] ライブラリ内容がガイド内容に沿っていることを確認しました！
- [x] 静的解析の指摘0件を確認しました！
- [x] 全自動テストの成功を確認しました！
- [x] テストカバレッジ100%を確認しました！

# Message to reviewers (レビュアーへのメッセージ)

- [x] ガイドに要件と使い方が書かれていますか？
- [x] ガイドに対応するプロダクションコードと自動テストコードが作成されていますか？
- [x] README を見てローカルでの開発環境をセットアップできそうですか？
- [x] コードは読みやすいですか？
- [x] 他に必要なテスト項目はありますか？

2022-10-22 15:47 UTC, kiyohome requested changes

2022-10-22 15:47 UTC, kiyohome commented on Runtime/ISceneTransitioner.cs
> +        event Action<TScene> OnSceneChanged;
シーンが遷移された時にinvokeしているので`OnSceneTransitioned`かと思いました。

2022-10-22 15:47 UTC, kiyohome commented on Runtime/ISceneTransitionConfiguration.cs
> +        public List<TPage> _pageNames = new List<TPage>();
UniduxのPageとSceneの概念だと思いますが反対な感じがします。
https://tech.mobilefactory.jp/entry/2018/12/10/163322
UniduxはPageとScene（=Unity Scene）みたいです。
ExtrealではSceneとUnitySceneにして使い勝手を見てみようと思います。

2022-10-22 15:47 UTC, kiyohome commented on Runtime/ISceneTransitionConfiguration.cs
> +        List<TPage> PermanentNames { get; }
シーン遷移は状態管理という意味合いの機能ではないので永続という用語だと分かりにくいように思います。Uniduxはpermanentですが。
全シーンで共通して使うUnityシーンを定義するとこだと思うのでcommonUnityScenesとかでしょうか。

2022-10-22 15:47 UTC, kiyohome commented on Runtime/ISceneTransitionConfiguration.cs
> +    public interface ISceneTransitionConfiguration<TPage, TScene>
シーン遷移機能の設定というより、シーン構成の設定だと思うのでSceneConfigurationだけでよいように思います。

2022-10-22 15:47 UTC, kiyohome commented on Runtime/ISceneTransitioner.cs
> +        UniTask PushAsync(TScene scene);
PushとPopはどのようなアプリ要件の時に使う想定でしょうか？
戻り先が複数あるような場合でしょうか？

2022-10-22 15:47 UTC, kiyohome commented on Runtime/ISceneTransitioner.cs
> +        UniTask PopAsync();
履歴がない場合の振る舞いをドキュメンテーションコメントに書いておいた方がよいと思います。

2022-10-22 15:47 UTC, kiyohome commented on Runtime/SceneTransitioner.cs
> +                return;
アプリの実装ミスだと思うのでInvalidOperationみたいな例外を投げた方がいいと思います。
これに関連しDebugレベルでシーン遷移の呼び出し（replace/push/pop/reset）をログに出しておいた方が開発しやすいように思います。

2022-10-22 15:47 UTC, kiyohome commented on Runtime/SceneTransitioner.cs
> +        public SceneTransitioner(ISceneTransitionConfiguration<TPage, TScene> configuration)
間違った使い方をすぐに検知できるようにconfigurationがnullでない、少なくとも1つ以上のシーンが入っているあたりはチェックしておいた方がいいと思います。

2022-10-23 01:09 UTC, kiyohome requested changes

2022-10-23 01:09 UTC, kiyohome commented on Runtime/ISceneTransitioner.cs
> +        void Reset();
Resetはいつ使う想定でしょうか？

2022-10-23 08:08 UTC, kiyohome requested changes

2022-10-23 08:08 UTC, kiyohome commented on Runtime/ISceneTransitionConfiguration.cs
> +    public interface ISceneTransitionConfiguration<TPage, TScene>
Configurationも省略したConfigでいいと思います。
SceneConfig

2022-10-24 00:40 UTC, sus-taguchi-t commented on Runtime/ISceneTransitioner.cs
> +        event Action<TScene> OnSceneChanged;
そちらの方が直感的に分かりやすいので変更します。

2022-10-24 00:41 UTC, sus-taguchi-t commented on Runtime/ISceneTransitionConfiguration.cs
> +        public List<TPage> _pageNames = new List<TPage>();
確かにそちらの命名の方が Extreal に合っている気がします。
変更します。

2022-10-24 00:44 UTC, sus-taguchi-t commented on Runtime/ISceneTransitionConfiguration.cs
> +        List<TPage> PermanentNames { get; }
確かに直感的な名前の方が分かりやすいのでその命名で良いと思います。
変更します。

2022-10-24 00:45 UTC, sus-taguchi-t commented on Runtime/ISceneTransitionConfiguration.cs
> +    public interface ISceneTransitionConfiguration<TPage, TScene>
良いと思います。
変更します。

2022-10-24 00:48 UTC, sus-taguchi-t commented on Runtime/ISceneTransitioner.cs
> +        UniTask PushAsync(TScene scene);
正直あまりイメージできていないです。
SampleApp でも `Replace()` のみしか使用していませんでした。
例えば「戻る」ボタンを押したときにわざわざ戻り先を指定しなくても `Pop()` で期待した画面に遷移できるとかでしょうか。

2022-10-24 00:49 UTC, sus-taguchi-t commented on Runtime/ISceneTransitioner.cs
> +        UniTask PopAsync();
確かにそれは必須だと思います。
追記します。

2022-10-24 00:51 UTC, sus-taguchi-t commented on Runtime/SceneTransitioner.cs
> +                return;
確かに例外は必須だと思います。
ログに関しては完全に実装漏れです。
追加します。

2022-10-24 00:53 UTC, sus-taguchi-t commented on Runtime/SceneTransitioner.cs
> +        public SceneTransitioner(ISceneTransitionConfiguration<TPage, TScene> configuration)
確かにそれは必須だと思います。
追加します。

2022-10-24 00:55 UTC, sus-taguchi-t commented on Runtime/ISceneTransitioner.cs
> +        void Reset();
正直あまりイメージできていないです。
SampleApp でも `Replace()` のみしか使用していませんでした。
例えば「戻る」ボタンが存在しないシーンでメモリ使用量を減らすために `Reset()` で `sceneHistory` のメモリをクリアするとかでしょうか。

2022-10-24 01:16 UTC, kiyohome commented on Runtime/ISceneTransitioner.cs
> +        void Reset();
Resetは複数のシーン遷移の塊がある場合に使う想定としてテストとガイドを追加しましょう。
Replace＋Resetで大きな遷移、その中でPush/Popするようなイメージ。

2022-10-24 04:52 UTC, kiyohome commented on Runtime/ISceneTransitioner.cs
> +        event Action<TScene> OnSceneChanged;
リネームしました。
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/3/commits/6aa6a992ec339e210f6a527638e8527832f4a553

2022-10-24 04:52 UTC, kiyohome commented on Runtime/ISceneTransitionConfiguration.cs
> +        public List<TPage> _pageNames = new List<TPage>();
リネームしました。
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/3/commits/6aa6a992ec339e210f6a527638e8527832f4a553

2022-10-24 04:52 UTC, kiyohome commented on Runtime/ISceneTransitionConfiguration.cs
> +        List<TPage> PermanentNames { get; }
リネームしました。
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/3/commits/6aa6a992ec339e210f6a527638e8527832f4a553

2022-10-24 04:53 UTC, kiyohome commented on Runtime/ISceneTransitionConfiguration.cs
> +    public interface ISceneTransitionConfiguration<TPage, TScene>
リネームしました。
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/3/commits/6aa6a992ec339e210f6a527638e8527832f4a553

2022-10-24 04:53 UTC, kiyohome commented on Runtime/ISceneTransitioner.cs
> +        UniTask PushAsync(TScene scene);
了解です！

2022-10-24 04:56 UTC, kiyohome commented on Runtime/ISceneTransitioner.cs
> +        void Reset();
ガイドはPRにコメント入れました。
https://github.com/extreal-dev/Extreal.Guide/pull/12#pullrequestreview-1152537535

2022-10-24 06:24 UTC, kiyohome commented on Runtime/ISceneTransitioner.cs
> +        UniTask PopAsync();
追記しました。
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/3/commits/7905aa37d6fb4e82cc0cbd641a70ce77f2204b56

2022-10-24 06:24 UTC, kiyohome commented on Runtime/SceneTransitioner.cs
> +                return;
履歴ないときのPop呼び出しは例外スローするようにしました。
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/3/commits/7905aa37d6fb4e82cc0cbd641a70ce77f2204b56

2022-10-24 07:17 UTC, kiyohome commented on Runtime/SceneTransitioner.cs
> +                return;
ログ出力を入れました。
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/3/commits/ddc2149412d3958b9e31008389d276c44c608565

2022-10-24 08:10 UTC, kiyohome commented on Runtime/SceneTransitioner.cs
> +        public SceneTransitioner(ISceneTransitionConfiguration<TPage, TScene> configuration)
シーン設定が不正な場合は例外を出すように変更しました。
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/3/commits/4f735c93700eced872331fcb58e0545617749940

2022-10-24 08:11 UTC, kiyohome commented on Runtime/ISceneTransitioner.cs
> +        void Reset();
Resetするとクリアするだけなのでテストは不要な気がしてきました。
ガイド追記のみにします。

2022-10-25 00:29 UTC, sus-taguchi-t commented on Runtime/ISceneTransitioner.cs
> +        event Action<TScene> OnSceneChanged;
確認しました。

2022-10-25 00:56 UTC, sus-taguchi-t commented on Runtime/ISceneTransitionConfiguration.cs
> +        public List<TPage> _pageNames = new List<TPage>();
確認しました。

2022-10-25 00:57 UTC, sus-taguchi-t commented on Runtime/ISceneTransitionConfiguration.cs
> +        List<TPage> PermanentNames { get; }
確認しました。

2022-10-25 00:58 UTC, sus-taguchi-t commented on Runtime/ISceneTransitionConfiguration.cs
> +    public interface ISceneTransitionConfiguration<TPage, TScene>
確認しました。

2022-10-25 03:07 UTC, sus-taguchi-t commented on Runtime/ISceneTransitioner.cs
> +        UniTask PopAsync();
確認しました。

2022-10-25 03:11 UTC, sus-taguchi-t commented on Runtime/SceneTransitioner.cs
> +                return;
確認しました。

2022-10-25 03:14 UTC, sus-taguchi-t commented on Runtime/SceneTransitioner.cs
> +        public SceneTransitioner(ISceneTransitionConfiguration<TPage, TScene> configuration)
ドキュメンテーションコメントに Exception の情報は入れないのでしょうか？

2022-10-25 03:14 UTC, sus-taguchi-t commented on Runtime/ISceneTransitioner.cs
> +        void Reset();
分かりました。

2022-10-25 05:13 UTC, kiyohome commented on Runtime/SceneTransitioner.cs
> +        public SceneTransitioner(ISceneTransitionConfiguration<TPage, TScene> configuration)
入れましたー
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/3/commits/083475bf492aa6750d2870d36f87b0dd7f209d26

2022-10-25 05:35 UTC, sus-taguchi-t commented on Runtime/SceneTransitioner.cs
> +        public SceneTransitioner(ISceneTransitionConfiguration<TPage, TScene> configuration)
確認しました。

2022-10-25 05:42 UTC, kiyohome approved these changes
LGTM

2022-10-25 05:42 UTC, merged