Change coding according to analyzer
extreal-dev/Extreal.Core.SceneTransition pull request #5
Opened 2022-10-26 08:14 UTC by sus-taguchi-t

# Describe Your Changes (なんの変更を加えましたか?)

- 静的解析に合わせてコードを変更した

# What did you verify? (何を確認しましたか?)

- [x] Verified that processing for invalid arguments and invalid method calls is included (無効な引数や無効なメソッド呼び出しに対する処理が入っていることを確認しました)
- [x] Verified that debug logs are being output to show behavior at runtime (実行時の動作が分かるようなデバッグログを出力していることを確認しました)
- [x] Verified that no problems were found in the static analysis (静的解析で問題が見つからないことを確認しました)
- [x] Verified that all tests succeeded (全てのテストが成功することを確認しました)
- [x] Verified that test coverage is 100% (テストカバレッジが100%になることを確認しました)

# Message to reviewers (レビュアーへのメッセージ)

2022-10-26 08:25 UTC, kiyohome requested changes

2022-10-26 08:25 UTC, kiyohome commented on Tests/Runtime/SceneTransitionTest.cs
> +        public void Dispose() => sceneTransitioner.OnSceneTransitioned -= OnSceneTransitioned;
今回の修正とは関係ないのですみませんが、UnityTearDownにした方がいいと思います。

2022-10-26 08:36 UTC, sus-taguchi-t commented on Tests/Runtime/SceneTransitionTest.cs
> +        public void Dispose() => sceneTransitioner.OnSceneTransitioned -= OnSceneTransitioned;
`TearDown` は 1 フレームで（同期的に）処理ができる場合、
`UnityTearDown` は複数フレーム間にわたって処理を行う場合、
だと思うので、今回は `TearDown` のままでも良いのかなと思いました。
[参考](https://docs.unity3d.com/Packages/com.unity.test-framework@1.1/manual/reference-unitysetup-and-unityteardown.html)

2022-10-26 08:42 UTC, kiyohome commented on Tests/Runtime/SceneTransitionTest.cs
> +        public void Dispose() => sceneTransitioner.OnSceneTransitioned -= OnSceneTransitioned;
UnitySetUpに対する処理に見えたのでUnityTearDownにした方がいいと思いました。
合わせるか、コメントで説明するかしないと毎回同じ質問を受けそうな気がします。

2022-10-27 02:06 UTC, sus-taguchi-t commented on Tests/Runtime/SceneTransitionTest.cs
> +        public void Dispose() => sceneTransitioner.OnSceneTransitioned -= OnSceneTransitioned;
形式を統一するために `UnitySetUp` `UnityTearDown` のみを使用することにしました。
https://github.com/extreal-dev/Extreal.Core.SceneTransition/pull/5/commits/da94d957de199fd7e70eb72dfd026f0d562f37bc

2022-10-27 02:19 UTC, kiyohome commented on Tests/Runtime/SceneTransitionTest.cs
> +        public void Dispose() => sceneTransitioner.OnSceneTransitioned -= OnSceneTransitioned;
LGTM

2022-10-27 02:19 UTC, kiyohome approved these changes

2022-10-27 02:20 UTC, merged